<?php
// Plugin definition
$plugin = array(
  'title' => t('ASF Front Page'),
  'icon' => 'radix-taylor-flipped.png',
  'category' => t('ASF'),
  'theme' => 'asf_front_page',
  'regions' => array(
    'sidebar' => t('Sidebar'),
    'main-header' => t('Main Header'),
    'concerts' => t('Concerts'),
    'block-alpha' => t('Block Alpha'),
    'block-bravo' => t('Block Bravo'),
    'block-charlie' => t('Block Charlie'),
    'block-delta' => t('Block Delta'),
    'block-echo' => t('Block Echo'),
    'block-foxtrot' => t('Block Foxtrot'),
    'block-golf' => t('Block Golf'),
    'block-hotel' => t('Block Hotel'),
    'sponsors' => t('Sponsors'),
    'location' => t('Location Block'),
    'newsletter' => t('Newsletter Block'),
    'footmenu' => t('Footer Menu'),
    'copy' => t('Copyright Block'),
  ),
);
